### ISSUE TITLE
Modify startup script to specify delta t

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#35]
The startup script for simulations needs to accept delta t as a parameter from the user so that simulations can be run at different speeds.

This is important later on when we want to run different scenarios as a kind of "system test suite".

**Comment by MikeHart85** [comment]
Might be something for a different ticket, but Freddie also mentioned he'd like to be able to change the delta t at runtime. For example, via a special PV.

**Comment by MichaelWedel** [comment]
Yes I think that's a different ticket. Currently this is the scope of the adapter, so I see a few options:
1. Modify `EpicsAdapter` to add a special PV.
2. Provide another adapter that implements this functionality, say `RuntimeControllableEpicsAdapter` for fans of long names.

The problem with both options is that they would tie this functionality to EPICS, while in fact this seems (at least to me) like a valid requirement for any simulation, regardless of the protocol.

Probably we can think of this as a second way of running simulations. There could be a simple server which is controlled by a simple command language over a protocol, for example ZeroMQ. This would be trivial to translate to some other protocol like EPICS. Coincidentally this sounds a lot like something that exists in the live-data-prototype.

**Comment by MichaelWedel** [comment]
This is how it's done in the live data prototype. There is an interface `Controllable` which defines what things that should be controllable at runtime via a network protocol should implement:

https://github.com/DMSC-Instrument-Data/live-data-prototype/blob/master/controllable.py

Then there is a server which exposes the defined properties and/or trigger functions via zmq:

https://github.com/DMSC-Instrument-Data/live-data-prototype/blob/master/parameter_control_server.py

Somewhere on my machine I have a general `Controllable -> EPICS`-adapter, I think the combination of those two components would cover the use case mentioned above.

**Comment by MikeHart85** [comment]
It is a feature we will likely want on all protocols, in some form, but I don't think it warrants creating an additional layer of separation, especially if it involves an additional server/client relation. 

There isn't that much functionality to add... and it seems like many things may vary from adapter to adapter.

For example: What exactly happens when you double the delta T? The simulation will run twice as fast of course... But what about the outputs? Should they get pumped out twice as fast as well? Or stay at once per (realtime) second like they currently are in the epics adapter? Will the answer be the same for all adapters? Will some adapters need a hard limit on how fast they pump out data?

**Comment by MichaelWedel** [comment]
This is exactly why I think separating this from the rest of the simulation is valid, it has to go into the general interface of `Adapter` so that a server like this can expose these parameters and their limits etc. uniformly.

Whatever approach we select in the end, it is well beyond passing a delta t parameter to the startup script, so it should be in a separate issue.

**Comment by MikeHart85** [comment]
Yeah, we should leave this discussion for when we get to that point... once we start implementing other adapters, like the ones Freddie wanted to try, it will probably be much clearer where we can optimize/organize better.
