### ISSUE TITLE
Re-structure modules

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#41]
After adding a few things it became more clear that our current module structure is not really well-suited. @MikeHart85 suggested the following modifications:
- `simulations.core`: move up one level
- `simulations`: rename to `devices`
- `scenarios`: rename to `setups`

I agree with this, in the end we'll have:

```
plankton
  adapters
  devices
  setups
  core
```

**Comment by MikeHart85** [comment]
Potential alternative name to consider for `adapters` might be `drivers`.

At least the way they are right now, `drivers` seems more descriptive since they actually drive the simulation, since they contain the main loop that repeatedly calls `process`, rather than just being an intermediate layer that adapts one protocol to another.

However, depending on what changes are introduced as part #39, this may not stay this way.
