### ISSUE TITLE
Deploy docker image via travis-ci

### ISSUE THREAD

**Issue by MichaelWedel** [ISISComputingGroup/lewis#44]
According to the travis [documentation](https://docs.travis-ci.com/user/docker/) it is possible to push docker images as part of the deployment process.

Once #14 is complete we should look into automating this process. Because it requires using a VM on the travis end, I expect this to be somewhat heavier so I'm not sure whether we should use this in our standard configuration that is built on each PR.

For now I suggest we package on each push to master as a kind of "nightly build". Ultimately we should decide on a release strategy (although that sounds like a big word now).

**Comment by MikeHart85** [comment]
DockerHub also has [automated build](https://docs.docker.com/docker-hub/builds) functionality. It works by linking a DockerHub repository to a GitHub or BitBucket repository. 

Compared to using Travis CI, there are the following advantages and disadvantages when using DockerHubs build process...
- It will pull the Dockerfile from the repository and make it available as a tab on DockerHub
- It will pull the ReadMe.md from the same directory as the Dockerfile and make it the long description on DockerHub
- It is limited to processing one build request per 5 minutes
- It won't run tests or anything like that

Since DockerHub doesn't currently provide an API for it, there is no way to make Travis upload the Dockerfile or ReadMe.md. 

Perhaps, eventually, the best approach will be to use Travis for building temporary images for testing with every commit (without pushing, or pushing with a "nightly" or "edge" tag or the like), and use DockerHub for periodically publishing stable releases.
